---
functional:
  - требование 1
  - требование 2
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional:
  - требование 5
  - требование 6
  - требование 7
  -требование 10
implicit:
  - Пользователь должен иметь возможность авторизации и регистрации на сайте.
  - Пользователь должен иметь возможность открывать на просмотр фотографии товара.
  - Пользователь должен иметь возможность читать и оставлять отзывы о товаре.
